name: Deploy Astro to Vercel

on:
  push:
    branches:
      - main  # Puedes cambiar esto si usas otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout Repo
        uses: actions/checkout@v3

      - name: â¬ Install Dependencies
        run: npm install

      - name: ğŸš€ Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
